# Generated by Django 4.2.20 on 2025-04-14 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("url_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="url_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="url_manager.urlitem",
                verbose_name="URL項目",
            ),
        ),
    ]
