# Generated by Django 5.2.7 on 2025-11-04 03:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('nickname', models.CharField(max_length=150, verbose_name='ニックネーム')),
                ('is_active', models.BooleanField(default=False, help_text='このユーザーがアクティブかどうかを指定します。アカウントを削除する代わりに、これを選択解除してください。', verbose_name='有効')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='メール認証日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('order', models.IntegerField(default=0, verbose_name='並び順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'コレクション',
                'verbose_name_plural': 'コレクション',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='トークン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'メール確認トークン',
                'verbose_name_plural': 'メール確認トークン',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='トークン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_tokens', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'パスワードリセットトークン',
                'verbose_name_plural': 'パスワードリセットトークン',
            },
        ),
        migrations.CreateModel(
            name='UrlItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='サムネイル')),
                ('check_type', models.CharField(choices=[('RSS', 'RSSフィード'), ('HTML_STANDARD', 'HTML標準'), ('HTML_CUSTOM', 'HTMLカスタム')], max_length=20, verbose_name='チェックタイプ')),
                ('html_selector', models.TextField(blank=True, help_text='複数のセレクタを指定する場合は、改行で区切ってください', null=True, verbose_name='HTMLセレクタ')),
                ('html_custom_condition', models.CharField(blank=True, choices=[('OR', 'いずれか変更 (OR)'), ('AND', 'すべて変更 (AND)')], default='OR', max_length=5, null=True, verbose_name='HTMLカスタム条件')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最終チェック日時')),
                ('last_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='最終更新日時')),
                ('last_content_hash', models.TextField(blank=True, null=True, verbose_name='最終コンテンツハッシュ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('error_count', models.IntegerField(default=0, verbose_name='エラー回数')),
                ('last_error_message', models.TextField(blank=True, null=True, verbose_name='最終エラーメッセージ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_items', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'URL項目',
                'verbose_name_plural': 'URL項目',
                'ordering': ['-last_updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('url_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookmark.urlitem', verbose_name='URL項目')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notification', models.BooleanField(default=True, verbose_name='メール通知')),
                ('browser_notification', models.BooleanField(default=True, verbose_name='ブラウザ通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
            },
        ),
        migrations.CreateModel(
            name='UrlItemCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_items', to='bookmark.collection', verbose_name='コレクション')),
                ('url_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='bookmark.urlitem', verbose_name='URL項目')),
            ],
            options={
                'verbose_name': 'URL項目-コレクション',
                'verbose_name_plural': 'URL項目-コレクション',
                'unique_together': {('url_item', 'collection')},
            },
        ),
    ]
