# Generated by Django 5.2.7 on 2025-11-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
    ]
