# Generated by Django 4.2.20 on 2025-04-14 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名前")),
                ("order", models.IntegerField(default=0, verbose_name="並び順")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "コレクション",
                "verbose_name_plural": "コレクション",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UrlItemCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="追加日時"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="url_items",
                        to="collection_manager.collection",
                        verbose_name="コレクション",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL項目-コレクション",
                "verbose_name_plural": "URL項目-コレクション",
            },
        ),
    ]
