# Generated by Django 4.2.20 on 2025-04-14 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("collection_manager", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="urlitemcollection",
            unique_together={("url_item", "collection")},
        ),
    ]
