# Generated by Django 4.2.20 on 2025-04-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrlItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000, verbose_name="URL")),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="サムネイル",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("RSS", "RSSフィード"),
                            ("HTML_STANDARD", "HTML標準"),
                            ("HTML_CUSTOM", "HTMLカスタム"),
                        ],
                        max_length=20,
                        verbose_name="チェックタイプ",
                    ),
                ),
                (
                    "html_selector",
                    models.TextField(
                        blank=True,
                        help_text="複数のセレクタを指定する場合は、改行で区切ってください",
                        null=True,
                        verbose_name="HTMLセレクタ",
                    ),
                ),
                (
                    "html_custom_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OR", "いずれか変更 (OR)"),
                            ("AND", "すべて変更 (AND)"),
                        ],
                        default="OR",
                        max_length=5,
                        null=True,
                        verbose_name="HTMLカスタム条件",
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終チェック日時"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終更新日時"
                    ),
                ),
                (
                    "last_content_hash",
                    models.TextField(
                        blank=True, null=True, verbose_name="最終コンテンツハッシュ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "error_count",
                    models.IntegerField(default=0, verbose_name="エラー回数"),
                ),
                (
                    "last_error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="最終エラーメッセージ"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "URL項目",
                "verbose_name_plural": "URL項目",
                "ordering": ["-last_updated_at", "-created_at"],
            },
        ),
    ]
