# Generated by Django 4.2.20 on 2025-04-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_manager', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlitem',
            name='pc_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pc_thumbnails/', verbose_name='PCサムネイル'),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='モバイルサムネイル'),
        ),
    ]
